Controllers/DepartmentController.cs
using Employee_Management_System.Models;
using Employee_Management_System.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Employee_Management_System.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly ConnectionString _db;

        public DepartmentController(ConnectionString db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<DepartmentViewModel> departments = await _db.Departments.Where(w => w.IsDeleted == false).Select(d => new DepartmentViewModel
            {
                ID = d.ID,
                Name = d.Name,
                Manager = d.DepartmentManager != null ? d.DepartmentManager.Name : "No Manager",
                Budget = d.Budget,
                Status = d.Status
            }).ToListAsync();
            return View(departments);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _db.Departments.AddAsync(department);
                    int save = await _db.SaveChangesAsync();

                    if (save == 0)
                        throw new Exception("Failed to Create Department!!!");

                    TempData["SuccessMessage"] = "Deprtment Created Successful!!!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return View(department);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                Department? department = await _db.Departments.FindAsync(id);
                ViewBag.Manager = await _db.Employees.Where(w => w.DepartmentID == id && w.IsDeleted == false).ToListAsync();

                if (department == null)
                    throw new Exception("Department not found!!!");

                return View(department);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(Department department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(department).State = EntityState.Modified;

                    int save = await _db.SaveChangesAsync();

                    if (save > 0)
                        TempData["SuccessMessage"] = "Department Updated Successfully!!!";
                    else
                        TempData["ErrorMessage"] = "Error: Failed to Update Department!!!";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Department? department = await _db.Departments.FindAsync(id);

                if (department == null)
                    throw new Exception("Department not found!!!");

                department.IsDeleted = true;

                _db.Entry(department).State = EntityState.Modified;

                int save = await _db.SaveChangesAsync();

                if (save > 0)

                    TempData["SuccessMessage"] = "Department Deleted Successfully!!!";
                else
                    TempData["ErrorMessage"] = "Error: Failed to Delete Department!!!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using Employee_Management_System.Models;
using Employee_Management_System.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace Employee_Management_System.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ConnectionString _db;

        public EmployeeController(ConnectionString db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employees = await _db.Employees.Where(w => w.IsDeleted == false)
                .Select(e => new EmployeeViewModel
                {
                    ID = e.ID,
                    Name = e.Name,
                    Email = e.Email,
                    Phone = e.Phone,
                    Position = e.Position,
                    Status = e.Status,
                    JoiningDate = e.JoiningDate,
                    Department = e.Department != null ? e.Department.Name : "No Department",
                    LatestScore = e.PerformanceReviews
                    .OrderByDescending(pr => pr.ReviewDate)
                    .Select(pr => (int?)pr.ReviewScore)
                    .FirstOrDefault()
                }).ToListAsync();

            ViewBag.Department = await _db.Departments.ToListAsync();
            return View(employees);
        }

        [HttpGet]
        public async Task<IActionResult> FilteredResults(
            string Name,
            int? Department,
            string Email,
            string Phone,
            string Position,
            int? MinScore,
            int? MaxScore,
            bool? Status)
        {
            var query = _db.Employees.AsQueryable();

            if (!string.IsNullOrWhiteSpace(Name))
                query = query.Where(e => e.Name.Contains(Name));

            if (Department.HasValue)
                query = query.Where(e => e.DepartmentID == Department);

            if (!string.IsNullOrWhiteSpace(Email))
                query = query.Where(e => e.Email.Contains(Email));

            if (!string.IsNullOrWhiteSpace(Phone))
                query = query.Where(e => e.Phone.Contains(Phone));

            if (!string.IsNullOrWhiteSpace(Position))
                query = query.Where(e => e.Position.Contains(Position));

            if (MinScore.HasValue)
                query = query.Where(e => e.PerformanceReviews.Any(pr => pr.ReviewScore >= MinScore));

            if (MaxScore.HasValue)
                query = query.Where(e => e.PerformanceReviews.Any(pr => pr.ReviewScore <= MaxScore));

            if (Status.HasValue)
                query = query.Where(e => e.Status == Status);

            query = query.Where(e => e.IsDeleted == false);

            var employees = await query.Select(e => new
            {
                e.ID,
                e.Name,
                e.Email,
                e.Phone,
                e.Position,
                e.Status,
                e.JoiningDate,
                Department = e.Department.Name,
                LatestScore = e.PerformanceReviews
                    .OrderByDescending(pr => pr.ReviewDate)
                    .Select(pr => (int?)pr.ReviewScore)
                    .FirstOrDefault()
            }).ToListAsync();

            return Json(employees);
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Department = await _db.Departments.ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Employee employee)
        {
            using (var transaction = _db.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        await _db.Employees.AddAsync(employee);

                        var department = await _db.Departments.FindAsync(employee.DepartmentID);
                        if (department == null)
                            throw new Exception("Invalid Department ID!!!");

                        int save = await _db.SaveChangesAsync();

                        if (save == 0)
                            throw new Exception("Department Assigning Error!!!");

                        transaction.Commit();

                        TempData["SuccessMessage"] = "Employee Created and Assigned to Department Successfully!!!";

                        return RedirectToAction("Index");
                    }
                }   
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = "Error: " + ex.Message;
                }
                ViewBag.Department = await _db.Departments.ToListAsync();
                return View(employee);
            }         
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                Employee? employee = await _db.Employees.FindAsync(id);

                if (employee == null)
                    throw new Exception("Employee not found!!!");

                ViewBag.Department = await _db.Departments.ToListAsync();
                return View(employee);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(Employee employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(employee).State = EntityState.Modified;

                    int save = await _db.SaveChangesAsync();

                    if (save > 0)

                        TempData["SuccessMessage"] = "Employee Updated Successfully!!!";
                    else
                        TempData["ErrorMessage"] = "Error: Failed to Update the Employee!!!";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                Employee? employee = await _db.Employees.FindAsync(id);

                if (employee == null)
                    throw new Exception("Employee not found!!!");

                employee.IsDeleted = true;

                _db.Entry(employee).State = EntityState.Modified;

                int save = await _db.SaveChangesAsync();

                if(save > 0)

                    TempData["SuccessMessage"] = "Employee Deleted Successfully!!!";
                else
                    TempData["ErrorMessage"] = "Error: Failed to Delete the Employee!!!";      
            }
            catch (Exception ex) 
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/PerformanceReviewController.cs
using Employee_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace Employee_Management_System.Controllers
{
    public class PerformanceReviewController : Controller
    {
        private readonly ConnectionString _db;

        public PerformanceReviewController(ConnectionString db)
        {
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<PerformanceReview> performances = await _db.PerformanceReviews.Where(w => w.IsDeleted == false).ToListAsync();

            ViewBag.Employee = await _db.Employees.ToListAsync();
            return View(performances);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Employee = await _db.Employees.ToListAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(PerformanceReview performance)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _db.PerformanceReviews.AddAsync(performance);
                    int save = await _db.SaveChangesAsync();

                    if (save == 0)
                        throw new Exception("Performance Review Entry Failed!!!");

                    TempData["SuccessMessage"] = "Performance Review Entry Successful!!!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            ViewBag.Employee = await _db.Employees.ToListAsync();
            return View(performance);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                PerformanceReview? performance = await _db.PerformanceReviews.FindAsync(id);

                if (performance == null)
                    throw new Exception("Performance Review not found!!!");

                ViewBag.Employee = await _db.Employees.ToListAsync();
                return View(performance);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(PerformanceReview performance)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Entry(performance).State = EntityState.Modified;

                    int save = await _db.SaveChangesAsync();

                    if (save > 0)
                        TempData["SuccessMessage"] = "Performance Review Updated Successfully!!!";
                    else
                        TempData["ErrorMessage"] = "Error: Failed to Update Performance Review!!!";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                PerformanceReview? performance = await _db.PerformanceReviews.FindAsync(id);

                if (performance == null)
                    throw new Exception("Performance Review not found!!!");

                performance.IsDeleted = true;

                _db.Entry(performance).State = EntityState.Modified;

                int save = await _db.SaveChangesAsync();

                if (save > 0)

                    TempData["SuccessMessage"] = "Performance Review Deleted Successfully!!!";
                else
                    TempData["ErrorMessage"] = "Error: Failed to Delete Performance Review!!!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error: " + ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> GetAvgPerformanceScorePerDepartment()
        {
            try
            {
                var connection = _db.Database.GetDbConnection();
                await connection.OpenAsync();

                using (var command = connection.CreateCommand())
                {
                    command.CommandText = "EXEC sp_AvgPerformanceScorePerDepartment";
                    command.CommandType = System.Data.CommandType.Text;

                    var result = new List<dynamic>();

                    using (var reader = await command.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            result.Add(new
                            {
                                DepartmentName = reader["DepartmentName"].ToString(),
                                AvgPerformanceScore = reader["AvgPerformanceScore"] != DBNull.Value
                                    ? Convert.ToDouble(reader["AvgPerformanceScore"])
                                    : (double?)null
                            });
                        }
                    }
                    TempData["result"] = JsonConvert.SerializeObject(result);
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Error: {ex.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management System</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <style>
        a.nav-link:hover {
            background-color: #e6ac00;
            color: white;
            text-decoration: none;
            display: inline-block;
            font-weight: bold;
        } 
    </style>
</head>
<body class ="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PerformanceReview" asp-action="Index">Performance Review</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PerformanceReview" asp-action="GetAvgPerformanceScorePerDepartment">Average Score (Department-wise)</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="app-main">
        <!--begin::App Content Header-->
        <div class="app-content">
            <!--begin::Container-->
            <div class="container-fluid">
                <!--begin::Row-->
                <div class="row">
                    <!--begin::Col-->
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <h5 style="padding-top: 1%; color: red;">
                            @TempData["ErrorMessage"]
                        </h5>
                    }
                    else if (TempData["SuccessMessage"] != null)
                    {
                        <h5 id="popup" style="padding-top: 1%; color: green;">
                            @TempData["SuccessMessage"]
                        </h5>
                    }
                    <div class="col-lg-12" style="padding: 1%;">
                        <!--begin::Small Box Widget 1-->
                        @RenderBody()
                    </div> <!--end::Col-->
                </div> <!--end::Row-->
            </div> <!--end::Container-->
        </div> <!--end::App Content-->
    </main> <!--end::App Main--> <!--begin::Footer-->

    <footer class="border-top footer text-muted mt-auto ms-auto">
        <!--begin::To the end-->
        <div class="float-end d-none d-sm-inline" style="padding-bottom:1%;">
            &copy;2024 - <i>Developed by - </i>
            <a class="text-decoration-none" href="https://www.linkedin.com/in/mahmudul-hasan-bari">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401m-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4" />
                </svg> <b>Mahmudul Hasan Bari</b>&nbsp;&nbsp;
            </a>
        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
    <script>
        new DataTable('#example');
    </script>
    <script>
        $(document).ready(function () {
            $("#popup").fadeOut(4000);
        });
    </script>
</body>
</html>